### ISSUE TITLE
The HUD is coming back for no reason

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#126] opened 2021-04-07 23:33 UTC
These parts (in yellow) come back all the time while driving and therefore we have more than the "Hide at" ! evosc 0.99.16
![Uploading 
![Sans titre](https://user-images.githubusercontent.com/15847867/113947174-53536000-980a-11eb-9724-d097a9109217.png)

**Comment by brakerb** [comment] 2021-04-25 12:26
Hey, that is caused by the servers widget. It calls a function that makes it reapear after 20s.
It is fixed in the latest version, I'll merge with master so it goes away.

**Closed by brakerb** 2021-04-25 12:26 UTC
